# Generated by Django 4.2.7 on 2023-11-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('snils', models.CharField(max_length=100)),
                ('polis', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('attachment', models.CharField(max_length=100)),
                ('fluorography', models.CharField(max_length=100)),
                ('d_accounting', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
