# Generated by Django 4.2.7 on 2023-11-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Pacient',
        ),
    ]
